import torch
import torch.nn as nn

class PumpCurvePredicate(nn.Module):
    """
    Substitutes standard Hazen-Williams limitations on actuator components driven fundamentally 
    by strict quadratic manufacturer formulations \DeltaH_{jl, t} = A Q^2 + B Q + C.
    """
    def __init__(self, pump_list: list, pump_curves: dict):
        """
        Logical translation mapping manufacturer variables.
        
        Args:
            pump_list (list): Filtered subset indexing explicit non-gravitational pressure additions.
            pump_curves (dict): Configuration mapping tuple (j, l) directly to (A, B, C) variables.
        """
        super().__init__()
        self.pump_list = pump_list
        self.pump_curves = pump_curves
        
        self.tau_min = 0.01
        self.tau_max = 1.0
        self.tau_raw = nn.Parameter(torch.zeros(len(pump_list)))

    def get_temperatures(self) -> torch.Tensor:
        """
        Identical sigmoid limits restricting edge logic inflation identically.
        """
        sig = torch.sigmoid(self.tau_raw)
        return self.tau_min + (self.tau_max - self.tau_min) * sig

    def forward(self, h_decoded: dict, q_decoded: dict) -> dict:
        """
        Equation 27 evaluating limits across \phi_{pump}(jl, t).
        """
        phi_pump = {}
        temperatures = self.get_temperatures()
        
        for idx, edge in enumerate(self.pump_list):
            j, l = edge
            h_j = h_decoded.get(j, 0.0)
            h_l = h_decoded.get(l, 0.0)
            q_jl = q_decoded.get(edge, 0.0)
            
            # H_{jl, t} = h_l - h_j (Head generated by the pump)
            delta_h = h_l - h_j
            
            A, B, C = self.pump_curves.get(edge, (0.0, 0.0, 0.0))
            
            expected_head = A * (q_jl ** 2) + B * q_jl + C
            residual = delta_h - expected_head
            
            tau_jl = temperatures[idx]
            phi_pump[edge] = torch.exp(- (residual ** 2) / (tau_jl ** 2))
            
        return phi_pump
